#!/bin/bash
echo "===== DIFF VIEW: Double Quotes → Single Quotes ====="
echo ""
echo "Lines with changes (- = old with double quotes, + = new with single quotes):"
echo ""
echo "--- OLD (double quotes)"
echo "+++ NEW (single quotes)"
echo ""
echo "@@ Variables @@"
echo "-    const FLAG_NAME = \"ktlDevPopupShortcutsAttached\";"
echo "+    const FLAG_NAME = 'ktlDevPopupShortcutsAttached';"
echo ""
echo "-    const POPOVER_SELECTOR = \"#kn-popover\";"
echo "+    const POPOVER_SELECTOR = '#kn-popover';"
echo ""
echo "-    const INPUT_BLOCK_SELECTOR = \"input, textarea, [contenteditable]\";"
echo "+    const INPUT_BLOCK_SELECTOR = 'input, textarea, [contenteditable]';"
echo ""
echo "-    const KEY_VIEW = \"v\";"
echo "+    const KEY_VIEW = 'v';"
echo ""
echo "-    const KEY_SCENE = \"s\";"
echo "+    const KEY_SCENE = 's';"
echo ""
echo "-    const KEY_FIELD = \"f\";"
echo "+    const KEY_FIELD = 'f';"
echo ""
echo "-    const KEY_OBJECT = \"o\";"
echo "+    const KEY_OBJECT = 'o';"
echo ""
echo "@@ getVisiblePopover function @@"
echo "-        return (\$p.length && \$p.is(\":visible\")) ? \$p : null;"
echo "+        return (\$p.length && \$p.is(':visible')) ? \$p : null;"
echo ""
echo "@@ clickCopyFor function @@"
echo "-        const \$line = \$popover.children(\"div\").children(\"div\").filter(function () {"
echo "+        const \$line = \$popover.children('div').children('div').filter(function () {"
echo ""
echo "-            const \$span = \$(this).children(\"span\").first();"
echo "+            const \$span = \$(this).children('span').first();"
echo ""
echo "-            const \$btn = \$line.children(\"a\").find(\".fa-copy\").first();"
echo "+            const \$btn = \$line.children('a').find('.fa-copy').first();"
echo ""
echo "@@ onKeydown function @@"
echo "-        const k = String(e.key || \"\").toLowerCase();"
echo "+        const k = String(e.key || '').toLowerCase();"
echo ""
echo "-            clickCopyFor(\"view_\");"
echo "+            clickCopyFor('view_');"
echo ""
echo "-            clickCopyFor(\"scene_\");"
echo "+            clickCopyFor('scene_');"
echo ""
echo "-            clickCopyFor(\"field_\");"
echo "+            clickCopyFor('field_');"
echo ""
echo "-            clickCopyFor(\"object_\");"
echo "+            clickCopyFor('object_');"
echo ""
echo "@@ Event binding @@"
echo "-    \$(document).off(\"keydown.ktlDevPopupShortcuts\");"
echo "+    \$(document).off('keydown.ktlDevPopupShortcuts');"
echo ""
echo "-    \$(document).on(\"keydown.ktlDevPopupShortcuts\", onKeydown);"
echo "+    \$(document).on('keydown.ktlDevPopupShortcuts', onKeydown);"
echo ""
echo "===== SUMMARY ====="
echo "Total changes: ALL double quotes (\") changed to single quotes (')"
echo "No backticks needed - no template literals in this code"
echo "No other code changes - only quote style"
